// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package job_template

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.ClientToken, b.ko.Spec.ClientToken) {
		delta.Add("Spec.ClientToken", a.ko.Spec.ClientToken, b.ko.Spec.ClientToken)
	} else if a.ko.Spec.ClientToken != nil && b.ko.Spec.ClientToken != nil {
		if *a.ko.Spec.ClientToken != *b.ko.Spec.ClientToken {
			delta.Add("Spec.ClientToken", a.ko.Spec.ClientToken, b.ko.Spec.ClientToken)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.JobTemplateData, b.ko.Spec.JobTemplateData) {
		delta.Add("Spec.JobTemplateData", a.ko.Spec.JobTemplateData, b.ko.Spec.JobTemplateData)
	} else if a.ko.Spec.JobTemplateData != nil && b.ko.Spec.JobTemplateData != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.JobTemplateData.ExecutionRoleARN, b.ko.Spec.JobTemplateData.ExecutionRoleARN) {
			delta.Add("Spec.JobTemplateData.ExecutionRoleARN", a.ko.Spec.JobTemplateData.ExecutionRoleARN, b.ko.Spec.JobTemplateData.ExecutionRoleARN)
		} else if a.ko.Spec.JobTemplateData.ExecutionRoleARN != nil && b.ko.Spec.JobTemplateData.ExecutionRoleARN != nil {
			if *a.ko.Spec.JobTemplateData.ExecutionRoleARN != *b.ko.Spec.JobTemplateData.ExecutionRoleARN {
				delta.Add("Spec.JobTemplateData.ExecutionRoleARN", a.ko.Spec.JobTemplateData.ExecutionRoleARN, b.ko.Spec.JobTemplateData.ExecutionRoleARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.JobTemplateData.JobDriver, b.ko.Spec.JobTemplateData.JobDriver) {
			delta.Add("Spec.JobTemplateData.JobDriver", a.ko.Spec.JobTemplateData.JobDriver, b.ko.Spec.JobTemplateData.JobDriver)
		} else if a.ko.Spec.JobTemplateData.JobDriver != nil && b.ko.Spec.JobTemplateData.JobDriver != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver) {
				delta.Add("Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver", a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver)
			} else if a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver != nil && b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint) {
					delta.Add("Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint", a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint)
				} else if a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint != nil && b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint != nil {
					if *a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint != *b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint {
						delta.Add("Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint", a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint)
					}
				}
				if len(a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments) != len(b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments) {
					delta.Add("Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments", a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments)
				} else if len(a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments) {
						delta.Add("Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments", a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters) {
					delta.Add("Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters", a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters)
				} else if a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters != nil && b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters != nil {
					if *a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters != *b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters {
						delta.Add("Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters", a.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters, b.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters)
					}
				}
			}
		}
		if len(a.ko.Spec.JobTemplateData.JobTags) != len(b.ko.Spec.JobTemplateData.JobTags) {
			delta.Add("Spec.JobTemplateData.JobTags", a.ko.Spec.JobTemplateData.JobTags, b.ko.Spec.JobTemplateData.JobTags)
		} else if len(a.ko.Spec.JobTemplateData.JobTags) > 0 {
			if !ackcompare.MapStringStringPEqual(a.ko.Spec.JobTemplateData.JobTags, b.ko.Spec.JobTemplateData.JobTags) {
				delta.Add("Spec.JobTemplateData.JobTags", a.ko.Spec.JobTemplateData.JobTags, b.ko.Spec.JobTemplateData.JobTags)
			}
		}
		if len(a.ko.Spec.JobTemplateData.ParameterConfiguration) != len(b.ko.Spec.JobTemplateData.ParameterConfiguration) {
			delta.Add("Spec.JobTemplateData.ParameterConfiguration", a.ko.Spec.JobTemplateData.ParameterConfiguration, b.ko.Spec.JobTemplateData.ParameterConfiguration)
		} else if len(a.ko.Spec.JobTemplateData.ParameterConfiguration) > 0 {
			if !reflect.DeepEqual(a.ko.Spec.JobTemplateData.ParameterConfiguration, b.ko.Spec.JobTemplateData.ParameterConfiguration) {
				delta.Add("Spec.JobTemplateData.ParameterConfiguration", a.ko.Spec.JobTemplateData.ParameterConfiguration, b.ko.Spec.JobTemplateData.ParameterConfiguration)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.JobTemplateData.ReleaseLabel, b.ko.Spec.JobTemplateData.ReleaseLabel) {
			delta.Add("Spec.JobTemplateData.ReleaseLabel", a.ko.Spec.JobTemplateData.ReleaseLabel, b.ko.Spec.JobTemplateData.ReleaseLabel)
		} else if a.ko.Spec.JobTemplateData.ReleaseLabel != nil && b.ko.Spec.JobTemplateData.ReleaseLabel != nil {
			if *a.ko.Spec.JobTemplateData.ReleaseLabel != *b.ko.Spec.JobTemplateData.ReleaseLabel {
				delta.Add("Spec.JobTemplateData.ReleaseLabel", a.ko.Spec.JobTemplateData.ReleaseLabel, b.ko.Spec.JobTemplateData.ReleaseLabel)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.KMSKeyARN, b.ko.Spec.KMSKeyARN) {
		delta.Add("Spec.KMSKeyARN", a.ko.Spec.KMSKeyARN, b.ko.Spec.KMSKeyARN)
	} else if a.ko.Spec.KMSKeyARN != nil && b.ko.Spec.KMSKeyARN != nil {
		if *a.ko.Spec.KMSKeyARN != *b.ko.Spec.KMSKeyARN {
			delta.Add("Spec.KMSKeyARN", a.ko.Spec.KMSKeyARN, b.ko.Spec.KMSKeyARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
