// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package job_template

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/emrcontainers"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/emrcontainers/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/emrcontainers-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.JobTemplate{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeJobTemplateOutput
	resp, err = rm.sdkapi.DescribeJobTemplate(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeJobTemplate", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.JobTemplate.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.JobTemplate.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.JobTemplate.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.JobTemplate.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.JobTemplate.Id != nil {
		ko.Status.ID = resp.JobTemplate.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.JobTemplate.JobTemplateData != nil {
		f5 := &svcapitypes.JobTemplateData{}
		if resp.JobTemplate.JobTemplateData.ConfigurationOverrides != nil {
			f5.ConfigurationOverrides = resp.JobTemplate.JobTemplateData.ConfigurationOverrides
		}
		if resp.JobTemplate.JobTemplateData.ExecutionRoleArn != nil {
			f5.ExecutionRoleARN = resp.JobTemplate.JobTemplateData.ExecutionRoleArn
		}
		if resp.JobTemplate.JobTemplateData.JobDriver != nil {
			f5f2 := &svcapitypes.JobDriver{}
			if resp.JobTemplate.JobTemplateData.JobDriver.SparkSubmitJobDriver != nil {
				f5f2f0 := &svcapitypes.SparkSubmitJobDriver{}
				if resp.JobTemplate.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint != nil {
					f5f2f0.EntryPoint = resp.JobTemplate.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint
				}
				if resp.JobTemplate.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments != nil {
					f5f2f0.EntryPointArguments = aws.StringSlice(resp.JobTemplate.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments)
				}
				if resp.JobTemplate.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters != nil {
					f5f2f0.SparkSubmitParameters = resp.JobTemplate.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters
				}
				f5f2.SparkSubmitJobDriver = f5f2f0
			}
			f5.JobDriver = f5f2
		}
		if resp.JobTemplate.JobTemplateData.JobTags != nil {
			f5.JobTags = aws.StringMap(resp.JobTemplate.JobTemplateData.JobTags)
		}
		if resp.JobTemplate.JobTemplateData.ParameterConfiguration != nil {
			f5f4 := map[string]*svcapitypes.TemplateParameterConfiguration{}
			for f5f4key, f5f4valiter := range resp.JobTemplate.JobTemplateData.ParameterConfiguration {
				f5f4val := &svcapitypes.TemplateParameterConfiguration{}
				if f5f4valiter.DefaultValue != nil {
					f5f4val.DefaultValue = f5f4valiter.DefaultValue
				}
				if f5f4valiter.Type != "" {
					f5f4val.Type = aws.String(string(f5f4valiter.Type))
				}
				f5f4[f5f4key] = f5f4val
			}
			f5.ParameterConfiguration = f5f4
		}
		if resp.JobTemplate.JobTemplateData.ReleaseLabel != nil {
			f5.ReleaseLabel = resp.JobTemplate.JobTemplateData.ReleaseLabel
		}
		ko.Spec.JobTemplateData = f5
	} else {
		ko.Spec.JobTemplateData = nil
	}
	if resp.JobTemplate.KmsKeyArn != nil {
		ko.Spec.KMSKeyARN = resp.JobTemplate.KmsKeyArn
	} else {
		ko.Spec.KMSKeyARN = nil
	}
	if resp.JobTemplate.Name != nil {
		ko.Spec.Name = resp.JobTemplate.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.JobTemplate.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.JobTemplate.Tags)
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	// Retrieve and set the tags for the JobTemplate resource
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		ko.Spec.Tags = rm.getTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN))
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeJobTemplateInput, error) {
	res := &svcsdk.DescribeJobTemplateInput{}

	if r.ko.Status.ID != nil {
		res.Id = r.ko.Status.ID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateJobTemplateOutput
	_ = resp
	resp, err = rm.sdkapi.CreateJobTemplate(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateJobTemplate", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Id != nil {
		ko.Status.ID = resp.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}

	rm.setStatusDefaults(ko)
	// Add tags to the JobTemplate resource after creation
	if ko.Spec.Tags != nil {
		// Mark the resource as not synced to trigger a requeue and apply tags
		rm.setStatusSynced(ctx, &resource{ko}, nil, nil, false)
	}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateJobTemplateInput, error) {
	res := &svcsdk.CreateJobTemplateInput{}

	if r.ko.Spec.ClientToken != nil {
		res.ClientToken = r.ko.Spec.ClientToken
	}
	if r.ko.Spec.JobTemplateData != nil {
		f1 := &svcsdktypes.JobTemplateData{}
		if r.ko.Spec.JobTemplateData.ConfigurationOverrides != nil {
			f1.ConfigurationOverrides = r.ko.Spec.JobTemplateData.ConfigurationOverrides
		}
		if r.ko.Spec.JobTemplateData.ExecutionRoleARN != nil {
			f1.ExecutionRoleArn = r.ko.Spec.JobTemplateData.ExecutionRoleARN
		}
		if r.ko.Spec.JobTemplateData.JobDriver != nil {
			f1f2 := &svcsdktypes.JobDriver{}
			if r.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver != nil {
				f1f2f0 := &svcsdktypes.SparkSubmitJobDriver{}
				if r.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint != nil {
					f1f2f0.EntryPoint = r.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPoint
				}
				if r.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments != nil {
					f1f2f0.EntryPointArguments = aws.ToStringSlice(r.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.EntryPointArguments)
				}
				if r.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters != nil {
					f1f2f0.SparkSubmitParameters = r.ko.Spec.JobTemplateData.JobDriver.SparkSubmitJobDriver.SparkSubmitParameters
				}
				f1f2.SparkSubmitJobDriver = f1f2f0
			}
			f1.JobDriver = f1f2
		}
		if r.ko.Spec.JobTemplateData.JobTags != nil {
			f1.JobTags = aws.ToStringMap(r.ko.Spec.JobTemplateData.JobTags)
		}
		if r.ko.Spec.JobTemplateData.ParameterConfiguration != nil {
			f1f4 := map[string]svcsdktypes.TemplateParameterConfiguration{}
			for f1f4key, f1f4valiter := range r.ko.Spec.JobTemplateData.ParameterConfiguration {
				f1f4val := &svcsdktypes.TemplateParameterConfiguration{}
				if f1f4valiter.DefaultValue != nil {
					f1f4val.DefaultValue = f1f4valiter.DefaultValue
				}
				if f1f4valiter.Type != nil {
					f1f4val.Type = svcsdktypes.TemplateParameterDataType(*f1f4valiter.Type)
				}
				f1f4[f1f4key] = *f1f4val
			}
			f1.ParameterConfiguration = f1f4
		}
		if r.ko.Spec.JobTemplateData.ReleaseLabel != nil {
			f1.ReleaseLabel = r.ko.Spec.JobTemplateData.ReleaseLabel
		}
		res.JobTemplateData = f1
	}
	if r.ko.Spec.KMSKeyARN != nil {
		res.KmsKeyArn = r.ko.Spec.KMSKeyARN
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return nil, ackerr.NewTerminalError(ackerr.NotImplemented)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteJobTemplateOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteJobTemplate(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteJobTemplate", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteJobTemplateInput, error) {
	res := &svcsdk.DeleteJobTemplateInput{}

	if r.ko.Status.ID != nil {
		res.Id = r.ko.Status.ID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.JobTemplate,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"ResourceNotFoundException":
		return true
	default:
		return false
	}
}
