---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-emrcontainers-writer
  namespace: default
rules:
- apiGroups:
  - emrcontainers.services.k8s.aws
  resources:
  - jobruns
  - jobtemplates
  - virtualclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - emrcontainers.services.k8s.aws
  resources:
  - jobruns
  - jobtemplates
  - virtualclusters
  verbs:
  - get
  - patch
  - update
